=== eva2468/webstack/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Company">
<xs:complexType>
<xs:sequence>
<xs:element name="Employee" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="Emp_ID"  type="xs:integer"></xs:element>
<xs:element name="Emp_Name"  type="xs:string"></xs:element>
<xs:element name="Emp_Age"  type="xs:integer"></xs:element>
<xs:element name="Emp_Salary"  type="MySal"></xs:element>
<xs:element name="Emp_email"  type="xs:string"></xs:element>
<xs:element name="Emp_phonenum"  type="xs:integer"></xs:element>
<xs:element name="Emp_designation"  type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:simpleType name="MySal">
<xs:restriction base="xs:integer">
<xs:minInclusive value="50000"></xs:minInclusive>
<xs:maxInclusive value="200000"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
</xs:schema>

=== eva2468/webstack/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="NewStylesheet.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="NewXMLSchema.xsd">
  <Employee>
  	<Emp_ID>101</Emp_ID>
    <Emp_Name>ABHIJITH</Emp_Name>
    <Emp_Age>22</Emp_Age>
    <Emp_Salary>55000</Emp_Salary>
    <Emp_email>abhijith232@gmail.com</Emp_email>
    <Emp_phonenum>9188578700</Emp_phonenum>
    <Emp_designation>Manager</Emp_designation>
  </Employee>
  <Employee>
   <Emp_ID>102</Emp_ID>
    <Emp_Name>ANUGRAH</Emp_Name>
    <Emp_Age>33</Emp_Age>
    <Emp_Salary>58000</Emp_Salary>
    <Emp_email>anughrah12@gmail.com</Emp_email>
    <Emp_phonenum>9188578700</Emp_phonenum>
    <Emp_designation>Project manager</Emp_designation>
  </Employee>
  <Employee>
  	<Emp_ID>103</Emp_ID>
    <Emp_Name>SIDHARTH</Emp_Name>
    <Emp_Age>32</Emp_Age>
    <Emp_Salary>60000</Emp_Salary>
    <Emp_email>sidharth456@gmail.com</Emp_email>
    <Emp_phonenum>716567879</Emp_phonenum>
    <Emp_designation>Manager</Emp_designation>
  </Employee>
  <Employee>
  	<Emp_ID>104</Emp_ID>
    <Emp_Name>Navin</Emp_Name>
    <Emp_Age>55</Emp_Age>
    <Emp_Salary>75000</Emp_Salary>
    <Emp_email>navin12@gmail.com</Emp_email>
    <Emp_phonenum>9188458700</Emp_phonenum>
    <Emp_designation> manager</Emp_designation>
  </Employee>
  <Employee>
   <Emp_ID>105</Emp_ID>
    <Emp_Name>Suraj</Emp_Name>
    <Emp_Age>45</Emp_Age>
    <Emp_Salary>65000</Emp_Salary>
    <Emp_email>suraj12@gmail.com</Emp_email>
    <Emp_phonenum>9188578700</Emp_phonenum>
    <Emp_designation> manager</Emp_designation>
  </Employee>
  <Employee>
   <Emp_ID>106</Emp_ID>
    <Emp_Name>Adith</Emp_Name>
    <Emp_Age>36</Emp_Age>
    <Emp_Salary>58000</Emp_Salary>
    <Emp_email>adith12@gmail.com</Emp_email>
    <Emp_phonenum>9188578700</Emp_phonenum>
    <Emp_designation>developer</Emp_designation>
  </Employee>
</Company>
